#! /usr/bin/env bash

hyperfine \
  --warmup 2 \
  --shell=none \
  --export-markdown="summary.md" \
  --sort="mean-time" \
  "bash bash/foo" \
  "c/foo" \
  "java -cp javaclass/ Foo" \
  "java java/Foo.java" \
  "kotlin kotlin/Foo.main.kts" \
  "kotlin -cp kotlinclass/ FooKt" \
  "lua lua/foo.lua" \
  "node nodejs/foo.js" \
  "nu nushell/foo.nu" \
  "python3 python/foo.py" \
  "ruby ruby/foo.rb" \
  "rust/foo" \
  "zsh zsh/foo" \
